version: '3.0'

services:
  backdotnet:
    build: back-dotnet/
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80/
  backjava:
    build: java-back/
    environment:
      - BASE_URL=http://backdotnet/
    ports:
      -"8081:8080"

 

